version: '3.8'

services:
  picpay-db-mysql:
    image: 'bitnami/mysql:latest'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_USERNAME=david
      - MYSQL_ROOT_PASSWORD=docker123
      - MYSQL_PASSWORD=dockerpicpay
      - MYSQL_DATABASE=picpay-db
